export const slugs = {
  addition: "addition",
  subtraction: "subtraction",
  multiplication: "multiplication",
  division: "division",
  algebra: "algebra",
  wordsIntoNumbers: "words-into-numbers",
  bidmas: "bidmas",


  // .
  numberMachines: "number-machines",
  romanNumerals: "roman-numerals",
  comparingNumbers: "comparing-numbers",
  nameOfAngle: "name-of-angle",
  indices: "indices",
  averages: "averages",
  primeNumbers: "prime-numbers",
  remainder: "remainder",
  timeMeasurement: "time-measurement",
  lcm_hcf: "lcm_hcf",
  simplifyingFractions: "simplifying-fractions",
  percentages: "percentages",
  fractions: "fractions",
  meanMedianModeRange: "mean-median-mode-range",
  conversions: "conversions",
  roundingOff: "rounding-off",
  speedDistanceTime: "speed-distance-time",
  ratios: "ratios",
  unitConversions: "unit-conversions",
  timeConversions: "time-conversions",
  discounts: "discounts",
  profitAndLoss: "profit-and-loss",
  simpleInterest: "simple-interest",
  divisibilityTests: "divisibility-tests",
  hourConversions_12_24: "12-24-hour-conversions",
  calendar: "calendar",
  numberSequences: "number-sequences",
  vat: "value-added-tax",
  incomeTax: "income-tax",
  inheritanceTax: "inheritance-tax",
  stampDuty: "stamp-duty",
  parkingCharges: "parking-charges",
  softDrinksSugarTax: "soft-drinks-sugar-tax",
  fuelDuty: "fuel-duty",
  petrolPump: "petrol-pump",
  utilityBills: "utility-bills",
  mealDeals: "meal-deals",
  busTickets: "bus-tickets",
  trainTravel: "train-travel",
  supermarketDeals: "supermarket-deals",
  foodutrition: "food--nutrition",
  goodHealth: "good-health",
  medicineDosage: "medicine-dosage",
  loanRepayments: "loan-repayments",
  travelCompany: "travel-company",
  recipeConundrum:"recipe-conundrum",
  betterValueDeals:"better-value-deals",
};
